spring:
  application:
    name: sb-ecom

  datasource:
    url: jdbc:postgresql://13.209.199.59:5432/ecommerce
    username: postgres
    password: "4444"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: 13.209.199.59
    port: 6379
    username: default
    password: ${REDIS_PASSWORD:}
    timeout: 3s

  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 3000000

  ecom:
    app:
      jwtCookieName: springBootEcom

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - email
              - profile
            # 기본값이기도 하지만 명시 OK
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:            # ← registration 과 같은 레벨
          google:
            issuer-uri: https://accounts.google.com

server:
  forward-headers-strategy: framework  # 프록시 뒤에서 baseUrl 재구성 안전장치

app:
  oauth2:
    redirect-success: ${OAUTH2_REDIRECT_SUCCESS:http://localhost:5173/}
    redirect-failure: ${OAUTH2_REDIRECT_FAILURE:http://localhost:5173/oauth/failure}
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://d24ygusmvzpq6k.cloudfront.net"

project:
  image: images/

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

frontend:
  url: "http://d24ygusmvzpq6k.cloudfront.net/"

image:
  base:
    url: "http://3.37.185.207/images"

logging:
  level:
    "org.springframework": DEBUG
    "org.hibernate.SQL": DEBUG
    "org.springframework.security": DEBUG
    "com.ecommerce.project": DEBUG
